### ISSUE TITLE
settings: missing custom batching fallback settings

### ISSUE THREAD

**Issue by ghost** [systopia/org.project60.sepa#15]

**Comment by bjendres** [comment]
Please add a description. I have no idea what this is about :)

**Comment by ghost** [comment]
Currently there are no standard-/fallback settings for creditors created using the settings page. This leads to javascript errors.

**Comment by bjendres** [comment]
Do you mean the creditor attributes? There won't be any, a user will have to enter them from scratch. 
Or do you mean the creditor's batching settings (like the notification period)? Those should be the currently valid general batching settings.

**Comment by ghost** [comment]
I mean the creditor's batching settings which are retrieved using the API (https://github.com/systopia/sepa_dd/blob/master/templates/CRM/Admin/Form/Setting/SepaSettings.tpl#L253). I have currently disabled the error handler because it returns an error for each setting (i.e. "_.OOFF.horizon", "_.OOFF.notice" etc.) that is not yet set. I need to make sure that these settings are created at runtime when someone enters a new creditor.
