### ISSUE TITLE
Firefox Update misinterprets number typed input

### ISSUE THREAD

**Issue by bjendres** [systopia/org.project60.sepa#8]
The SEPA Create Mandate from has input element of type `number` for the amount. The new update of Firefox now interprets this element as integer, while some documentation ( http://www.w3.org/TR/html-markup/input.number.html#input.number.attrs.type) clearly states it as being float. Now you cannot input floating point numbers any more.

As a workaround, you can set the value of Firefox's `dom.forms.number` in the `about:config` to `false`.

**Comment by ghost** [comment]
There is another workaround described here:
https://bugzilla.mozilla.org/show_bug.cgi?id=344616#c12

It seems that mozilla is not going to fix this issue anytime soon
